sudo: required
language: rust
rust:
  - nightly-2017-10-16
before_install:
  - sudo apt-get update -q || true
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - rustup component add rustfmt
script:
  - cargo build
  - cargo fmt -- --check
  - export DOCKER_REPO=fede1024/kafka-view

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker build -t $DOCKER_REPO . && docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $DOCKER_REPO
    fi
